{{- if .Values.cron.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "rust-healthcheck.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rust-healthcheck.name" . }}
    helm.sh/chart: {{ include "rust-healthcheck.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  schedule: {{ .Values.cron.schedule | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "rust-healthcheck.name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
        spec:
          restartPolicy: Never
          securityContext:
            runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
          containers:
            - name: rust-healthcheck
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                - "--config"
                - "/app/config/config.json"
              volumeMounts:
                - name: config
                  mountPath: /app/config
                  readOnly: true
          volumes:
            - name: config
              configMap:
                name: {{ include "rust-healthcheck.fullname" . }}-config
{{- end }}