apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
helmCharts:
  - name: rust-healthcheck
    path: ../../chart
    version: 0.1.0
    releaseName: dev
    namespace: dev
    valuesFile: values.yaml

